/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        lime: { DEFAULT: '#e8ff47', dark: '#c8e000' },
        bg: { DEFAULT: '#080808', card: '#111111' },
        // Premium Blog Colors
        "tertiary-fixed": "#e6e2d8",
        "on-primary": "#ffffff",
        "primary-container": "#4f6f5b",
        "on-secondary-fixed-variant": "#394b3f",
        "surface-bright": "#f2fcf3",
        "surface-tint": "#466552",
        "primary": "#375744",
        "inverse-on-surface": "#e9f3eb",
        "on-tertiary-container": "#ece8de",
        "deep-forest": "#111A15",
        "surface-variant": "#dbe5dd",
        "on-tertiary-fixed-variant": "#484740",
        "sage-accent": "#4F6F5B",
        "surface": "#f2fcf3",
        "primary-fixed-dim": "#accfb7",
        "surface-container-low": "#ecf6ed",
        "on-error-container": "#93000a",
        "outline": "#727973",
        "on-tertiary": "#ffffff",
        "on-secondary-container": "#56695c",
        "on-primary-fixed-variant": "#2e4d3b",
        "error": "#ba1a1a",
        "on-surface": "#141e18",
        "tertiary-fixed-dim": "#cac6bd",
        "surface-dim": "#d2ddd4",
        "on-primary-fixed": "#012112",
        "background-white": "#FFFFFF",
        "background": "#f2fcf3",
        "on-secondary": "#ffffff",
        "secondary": "#506356",
        "error-container": "#ffdad6",
        "surface-container-high": "#e0ebe2",
        "surface-container": "#e6f0e8",
        "tertiary-container": "#6a6860",
        "on-secondary-fixed": "#0e1f16",
        "inverse-primary": "#accfb7",
        "on-error": "#ffffff",
        "secondary-fixed": "#d3e8d8",
        "on-tertiary-fixed": "#1c1c16",
        "surface-cream": "#F4F0E6",
        "secondary-fixed-dim": "#b7cbbd",
        "surface-container-lowest": "#ffffff",
        "outline-variant": "#c2c8c1",
        "on-primary-container": "#cdf0d7",
        "tertiary": "#515049",
        "on-background": "#141e18",
        "primary-fixed": "#c7ebd2",
        "surface-container-highest": "#dbe5dd",
        "inverse-surface": "#29332d",
        "secondary-container": "#d3e8d8",
        "on-surface-variant": "#424843"
      },
      fontFamily: {
        syne: ['Syne', 'sans-serif'],
        mono: ['DM Mono', 'monospace'],
        // Premium Typography system
        "headline-md": ["Lora", "serif"],
        "headline-lg": ["Lora", "serif"],
        "code-md": ["JetBrains Mono", "monospace"],
        "headline-lg-mobile": ["Lora", "serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-xl": ["Lora", "serif"],
        "body-md": ["Inter", "sans-serif"]
      },
    },
  },
  plugins: [],
};
